add:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: media_player
    media_content_id:
      required: true
      example: "media-source://media_source/local/Muziek/Album"
      selector:
        text:
    media_content_type:
      required: true
      example: "music"
      selector:
        text:
    mode:
      default: add
      selector:
        select:
          translation_key: mode
          options:
            - replace
            - add
            - next
            - play
    title:
      selector:
        text:

play_index:
  fields:
    entity_id: &entity
      required: true
      selector:
        entity:
          domain: media_player
    item_id: &item_id
      selector:
        text:
    index: &index
      selector:
        number:
          min: 0
          max: 999
          mode: box

next:
  fields:
    entity_id: *entity

previous:
  fields:
    entity_id: *entity

remove:
  fields:
    entity_id: *entity
    item_id: *item_id
    index: *index

move:
  fields:
    entity_id: *entity
    item_id: *item_id
    from_index: *index
    to_index:
      required: true
      selector:
        number:
          min: 0
          max: 999
          mode: box

clear:
  fields:
    entity_id: *entity

set_shuffle:
  fields:
    entity_id: *entity
    shuffle:
      required: true
      selector:
        boolean:

set_repeat:
  fields:
    entity_id: *entity
    repeat:
      required: true
      selector:
        select:
          translation_key: repeat
          options:
            - "off"
            - all
            - one

get_queue:
  fields:
    entity_id: *entity
